services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=DATABASE_URL
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=VITE_APP_API_URL
    command: npm run dev --host 
