services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL}
    command: npm run dev
